[versions]
kotlin = "2.2.20-Beta2"
shadow = "8.3.0"
paper = "1.20.1-R0.1-SNAPSHOT"
runpaper = "2.3.1"

[libraries]
paper = { group = "io.papermc.paper", name = "paper-api", version.ref = "paper" }

[plugins]
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
runpaper = { id = "xyz.jpenilla.run-paper", version.ref = "runpaper" }
shadow = { id = "com.github.johnrengelman.shadow", version.ref = "shadow" }

#     id("xyz.jpenilla.run-paper") version "2.3.1"